/*******************************************************************************
 *     Specification-Driven-Predictive-Process-Monitoring
 *     Copyright (C) 2018 Ario Santoso (santoso.ario@gmail.com)
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
package org.astw.gui.modelpreparation.init;

import java.awt.Color;
import java.awt.GridLayout;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

import org.astw.analyticrules.AnalyticRuleSpec;
import org.astw.analyticrules.RuleSpec;
import org.astw.analyticrules.TargetExpression;
import org.astw.gui.modelpreparation.RuleSpecPanel.RuleSpecPanelType;

/**
 * 
 * @author Ario Santoso (santoso.ario@gmail.com)
 * @author Yasmin Khairina (yasminkhairina08@gmail.com)
 */

public class AnalyticRuleSpecSimpleViewerPanel extends JPanel{

	private AnalyticRuleSpec ars;
	
	public AnalyticRuleSpecSimpleViewerPanel(AnalyticRuleSpec ars){
		this.ars = ars;
		initComponents();
//		this.ruleNameLabel.setForeground(Color.BLUE);
//		this.ruleDescriptionLabel.setForeground(Color.BLUE);
		this.ruleName.setForeground(Color.DARK_GRAY);
		this.ruleDescription.setForeground(Color.DARK_GRAY);
	}
	
	
	public void refresh(){
	
		this.ruleName.setText(ars.getRuleName());
		this.ruleDescription.setText(ars.getRuleDescription());
	}

	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ruleNameLabel = new javax.swing.JLabel();
        ruleName = new javax.swing.JLabel();
        ruleDescriptionLabel = new javax.swing.JLabel();
        ruleDescription = new javax.swing.JLabel();

        ruleNameLabel.setText("Rule name:");

        ruleName.setText("");

        ruleDescriptionLabel.setText("Rule Description:");

        ruleDescription.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruleNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ruleName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(ruleDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ruleDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ruleNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruleName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruleDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruleDescription)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel ruleName;
    private javax.swing.JLabel ruleNameLabel;
    private javax.swing.JLabel ruleDescription;
    private javax.swing.JLabel ruleDescriptionLabel;
    // End of variables declaration            
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel defaultTargetExpression;
    private javax.swing.JLabel defaultTargetLabel;
    // End of variables declaration                   

}
