/*******************************************************************************
 *     Specification-Driven-Predictive-Process-Monitoring
 *     Copyright (C) 2018 Ario Santoso (santoso.ario@gmail.com)
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
package org.astw.gui.modelpreparation.init;

import java.awt.Color;
import java.awt.GridLayout;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

import org.astw.analyticrules.RuleSpec;
import org.astw.analyticrules.TargetExpression;
import org.astw.gui.modelpreparation.RuleSpecPanel.RuleSpecPanelType;

/**
 * 
 * @author Ario Santoso (santoso.ario@gmail.com)
 * @author Yasmin Khairina (yasminkhairina08@gmail.com)
 */

public class RuleSpecPanel extends JPanel{

	public enum RuleSpecPanelType {CONDITIONAL_TARGET_EXPRESSION, UNCONDITIONAL_TARGET_EXPRESSION};

	private RuleSpec ruleSpec;
	private TargetExpression targetExp;
	private RuleSpecPanelType ruleSpecPanelType;
	
	public RuleSpecPanel(RuleSpec ruleSpec){
		this.ruleSpec = ruleSpec;
		this.ruleSpecPanelType = RuleSpecPanelType.CONDITIONAL_TARGET_EXPRESSION;
		initComponentsConditionalTargetExpression();
		
//		this.conditionLabel.setForeground(Color.BLUE);
//		this.targetLabel.setForeground(Color.BLUE);
		this.conditionExpression.setForeground(Color.DARK_GRAY);
		this.targetExpression.setForeground(Color.DARK_GRAY);
		this.setForeground(Color.GREEN);
	}
	
	public RuleSpecPanel(TargetExpression targetExp){
		
		this.targetExp = targetExp;
		this.ruleSpecPanelType = RuleSpecPanelType.UNCONDITIONAL_TARGET_EXPRESSION;
		initComponentsUnconditionalTargetExpression();
//		this.defaultTargetLabel.setForeground(Color.BLUE);
		this.defaultTargetExpression.setForeground(Color.DARK_GRAY);
	}

	
//	public void setRuleSpecification(RuleSpec ruleSpec){
//				
//		this.conditionExpression.setText(ruleSpec.getCondition().toString());
//		this.targetExpression.setText(ruleSpec.getTarget().toString());
//	}
	
	public void refresh(){
		
		if(this.ruleSpecPanelType == RuleSpecPanelType.CONDITIONAL_TARGET_EXPRESSION){
			this.conditionExpression.setText(ruleSpec.getCondition().toString());
			this.targetExpression.setText(ruleSpec.getTarget().toString());
		}
		
		if(this.ruleSpecPanelType == RuleSpecPanelType.UNCONDITIONAL_TARGET_EXPRESSION){
			this.defaultTargetExpression.setText(this.targetExp.toString());
		}

	}

	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponentsConditionalTargetExpression() {

        conditionLabel = new javax.swing.JLabel();
        conditionExpression = new javax.swing.JLabel();
        targetLabel = new javax.swing.JLabel();
        targetExpression = new javax.swing.JLabel();

        conditionLabel.setText("Condition:");

        conditionExpression.setText("Condition Expression");

        targetLabel.setText("Target:");

        targetExpression.setText("Target Expression");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conditionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conditionExpression, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(targetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(targetExpression, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conditionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conditionExpression)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetExpression)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponentsUnconditionalTargetExpression() {

        defaultTargetLabel = new javax.swing.JLabel();
        defaultTargetExpression = new javax.swing.JLabel();

        defaultTargetLabel.setText("Default Target:");

        defaultTargetExpression.setText("Target Expression");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defaultTargetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(defaultTargetExpression, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(defaultTargetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defaultTargetExpression)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel conditionExpression;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JLabel targetExpression;
    private javax.swing.JLabel targetLabel;
    // End of variables declaration            
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel defaultTargetExpression;
    private javax.swing.JLabel defaultTargetLabel;
    // End of variables declaration                   

}
